import {layoutMetrics,planMetricEdits,applyMetricPlan,setKerningException} from '@wieslawsoltes/counterform-metrics';
import {parseFeatures,normalizeFeatureConditions,matchFeatureCondition,kerningValue,pairKey} from '@wieslawsoltes/counterform-opentype';
import {encodeCollection,readCollection,extractCollectionFace,extractCollectionFaces} from '@wieslawsoltes/counterform-binary';
import {download} from '@wieslawsoltes/counterform-storage';
import {toSVG,uid} from '@wieslawsoltes/counterform-geometry';
import {el,button,dialog,field} from './ui.js';

const svg=(tag,attributes={})=>{const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v]of Object.entries(attributes))e.setAttribute(k,String(v));return e;};
const statusBox=()=>{const s=el('p','cf-workflow-status');s.setAttribute('role','status');s.setAttribute('aria-label','Workflow status');s.setAttribute('aria-live','polite');return s;};
const action=(status,fn)=>async()=>{try{status.dataset.error='false';await fn();}catch(e){if(e.name!=='AbortError'){status.dataset.error='true';status.textContent=e.message;}}};
const number=(f,min,max)=>{const s=f.input.value.trim(),v=Number(s);if(!s||!Number.isFinite(v)||v<min||v>max)throw new RangeError(`${f.input.getAttribute('aria-label')}: enter ${min}…${max}`);return v;};

/** Every modal owns its listeners and worker key. Document replacement disposes it. */
function lifetime(app,d){
    const doc=app.doc,id=app.doc.data.id,masterId=app.editor.masterId,controller=new AbortController(),key=uid('workflow');
    const dispose=()=>{controller.abort();app.compiler.cancelKey(key);if(d.element.open)d.close();};app.disposables.push(dispose);
    const off=doc.changed.subscribe(()=>{if(doc.data.id!==id)dispose();});
    d.element.addEventListener('close',()=>{off();controller.abort();app.compiler.cancelKey(key);const i=app.disposables.indexOf(dispose);if(i>=0)app.disposables.splice(i,1);},{once:true});
    return {doc,masterId,key,signal:controller.signal,alive:()=>!controller.signal.aborted&&d.element.open&&d.element.isConnected,
        check(edit=true){if(controller.signal.aborted||!d.element.open||!d.element.isConnected)throw new DOMException('Editor closed','AbortError');if(app.doc!==doc||app.doc.data.id!==id||app.editor.masterId!==masterId||edit&&app.editor.readOnly)throw new Error('Document or source master changed. Reopen this editor.');}};
}
export function registerWorkflowCommands(app){
    app.commands.register({id:'metrics.editor',label:'Metrics string editor',keys:[],repeat:false,execute:()=>showMetricsEditor(app),enabled:()=>!app.editor.readOnly});
    app.commands.register({id:'features.variations',label:'Conditional OpenType features',keys:[],repeat:false,execute:()=>showFeatureVariations(app),enabled:()=>!app.editor.readOnly&&app.doc.data.axes.length>0});
    app.commands.register({id:'font.collection',label:'Font collection builder',keys:[],repeat:false,execute:()=>showCollectionBuilder(app)});
}

export function showMetricsEditor(app){
    const d=dialog('Metrics string editor',{wide:true,className:'cf-workflow-dialog',subtitle:'Edit source spacing and glyph-pair exceptions on the selected master. Slash notation selects unencoded glyphs. Every Apply is one undo transaction.'}),s=lifetime(app,d),status=statusBox();
    const line=field('Metrics text','HHOH AVAVA /A/V'),size=field('Metrics display size',112,{type:'range',min:40,max:240,step:1}),mode=field('Kerning display','on',{options:[{value:'on',label:'Kerning on'},{value:'off',label:'Kerning off'}]});
    const tools=el('div','cf-workflow-toolbar');tools.append(line.element,size.element,mode.element);
    const scroll=el('div','cf-metrics-scroll'),drawing=svg('svg',{'aria-label':'Source outline metrics strip',role:'img'}),choices=el('div','cf-metrics-choices');choices.setAttribute('role','toolbar');choices.setAttribute('aria-label','Metrics glyph selection');scroll.append(drawing);
    const metricRows=el('div','cf-metrics-table'),table=el('table','cf-table');table.setAttribute('aria-label','Metrics values');metricRows.append(table);
    const layout=el('div','cf-workflow-columns'),left=el('div','cf-workflow-main'),right=el('div','cf-workflow-properties'),selected=el('h3'),summary=el('p','cf-mono');left.append(tools,scroll,choices,metricRows);layout.append(left,right);
    const scope=field('Apply metrics to','selected',{options:[{value:'selected',label:'Selected glyph'},{value:'string',label:'All unique glyphs in string'}]}),lsb=field('Left sidebearing expression',''),rsb=field('Right sidebearing expression',''),advance=field('Advance width expression','');
    const pair=el('h3'),kern=field('Pair kerning value',0,{type:'number',min:-32768,max:32767,step:1}),pairStatus=el('p','cf-muted');
    right.append(selected,summary,scope.element,lsb.element,rsb.element,advance.element,el('p','cf-muted','Blank fields preserve current metrics. Use lsb("H") + 10, =H, =|H, or arithmetic. Formulas apply on demand; they are not live links.'));
    let run={items:[],advanceWidth:0,missing:[]},index=0,lastValidText=null;
    const choose=(next,focus=false)=>{index=Math.max(0,Math.min(run.items.length-1,next));renderSelection();paint();if(focus)choices.children[index]?.focus();};
    function renderSelection(){const item=run.items[index],previous=run.items[index-1];selected.textContent=item?item.name:'No glyph selected';summary.textContent=item&&!item.missing?`LSB ${item.lsb.toFixed(2)} · RSB ${item.rsb.toFixed(2)} · Advance ${item.advanceWidth.toFixed(2)}`:'Enter glyphs present in this source';
        for(const [i,b]of [...choices.children].entries()){b.tabIndex=i===index?0:-1;b.setAttribute('aria-pressed',String(i===index));}
        for(const row of table.querySelectorAll('tbody tr'))row.classList.toggle('selected',Number(row.dataset.index)===index);
        const valid=item&&!item.missing,validPair=valid&&previous&&!previous.missing;apply.disabled=!valid;setPair.disabled=removePair.disabled=!validPair;
        pair.textContent=validPair?`${previous.name} / ${item.name}`:'Select the right glyph of a pair';
        if(validPair){const pairs=s.doc.data.kerning[s.masterId]||{},override=Object.hasOwn(pairs,pairKey(previous.name,item.name))||Object.hasOwn(pairs,`${previous.name}/${item.name}`);kern.input.value=String(kerningValue(s.doc.data,s.masterId,previous.name,item.name));pairStatus.textContent=override?'Explicit glyph-pair exception':'Inherited group kerning, or zero';}else pairStatus.textContent='';
    }
    function paint(){const px=Number(size.input.value),scale=px/s.doc.info.unitsPerEm,asc=s.doc.info.ascender,desc=s.doc.info.descender;const minX=Math.min(0,...run.items.map(i=>i.x+i.lsb)),maxX=Math.max(1,run.advanceWidth,...run.items.map(i=>i.x+i.advanceWidth));const height=Math.max(1,asc-desc);
        drawing.setAttribute('viewBox',`${minX-30} ${-asc-50} ${maxX-minX+60} ${height+100}`);drawing.style.width=`${Math.max(200,(maxX-minX+60)*scale)}px`;drawing.style.height=`${(height+100)*scale}px`;drawing.replaceChildren();
        drawing.append(svg('line',{x1:minX-30,y1:0,x2:maxX+30,y2:0,class:'cf-metrics-baseline'}));
        for(const item of run.items){if(item.missing)continue;const group=svg('g',{transform:`translate(${item.x} 0)`});if(item.index===index)group.append(svg('rect',{x:0,y:-asc,width:Math.max(1,item.advanceWidth),height,class:'cf-metrics-highlight'}));group.append(svg('path',{d:toSVG(s.doc.resolve(item.glyphId,s.masterId)),transform:'scale(1 -1)',class:'cf-metrics-ink'}));group.append(svg('line',{x1:0,y1:-asc,x2:0,y2:-desc,class:'cf-metrics-side'}));drawing.append(group);}
    }
    function refresh(){s.check(false);const next=layoutMetrics(s.doc,s.masterId,line.input.value,{kerning:mode.input.value==='on'});if(next.items.length>256)throw new RangeError('The interactive metrics strip supports 256 positions; split longer proof strings');run=next;lastValidText=line.input.value;index=Math.min(index,Math.max(0,run.items.length-1));
        // Reuse buttons by occurrence, including repeated glyph IDs. Do not steal field focus.
        while(choices.children.length>run.items.length)choices.lastChild.remove();run.items.forEach((item,i)=>{let b=choices.children[i];if(!b){b=button('',()=>choose(i),{className:'cf-metrics-choice'});choices.append(b);}b.textContent=item.name;b.dataset.glyphId=item.glyphId||'';b.setAttribute('aria-label',`${item.name} at position ${i+1}`);});
        table.replaceChildren();const head=el('thead'),hr=el('tr'),body=el('tbody');for(const name of ['Position','Glyph','Left','Right','Advance','Kern before'])hr.append(el('th','',name));head.append(hr);
        for(const item of run.items){const row=el('tr');row.dataset.index=String(item.index);for(const value of [item.index+1,item.name,item.lsb.toFixed(2),item.rsb.toFixed(2),item.advanceWidth.toFixed(2),item.kernBefore])row.append(el('td','',String(value)));body.append(row);}table.append(head,body);renderSelection();paint();
        if(run.missing.length){status.dataset.error='true';status.textContent='Missing glyphs: '+run.missing.map(i=>i.name).join(', ');}else {status.dataset.error='false';status.textContent=`${run.items.length} positions · ${run.advanceWidth.toFixed(2)} font units · ${s.doc.data.masters.find(m=>m.id===s.masterId).name}`;}
    }
    const apply=button('Apply metrics',action(status,()=>{s.check();if(line.input.value!==lastValidText)throw new Error('Correct the metrics text before applying');const item=run.items[index];if(!item||item.missing)throw new Error('Select an existing glyph');const fields={};for(const [key,f]of [['lsb',lsb],['rsb',rsb],['advanceWidth',advance]])if(f.input.value.trim())fields[key]=f.input.value.trim();
        const ids=scope.input.value==='string'?[...new Set(run.items.filter(i=>!i.missing).map(i=>i.glyphId))]:[item.glyphId];const plan=planMetricEdits(s.doc,s.masterId,ids.map(glyphId=>({glyphId,...fields})));app.history.execute('Apply metrics expressions',()=>applyMetricPlan(s.doc,plan));status.textContent=`Updated ${ids.length} glyph${ids.length===1?'':'s'} in one transaction.`;}),{className:'primary'});
    function editPair(value){s.check();if(line.input.value!==lastValidText)throw new Error('Correct the metrics text before applying');const l=run.items[index-1],r=run.items[index];if(!l||!r||l.missing||r.missing)throw new Error('Select two existing adjacent glyphs');app.history.execute(value===null?'Remove kerning exception':'Set kerning exception',()=>setKerningException(s.doc,s.masterId,l.glyphId,r.glyphId,value));}
    const setPair=button('Set pair exception',action(status,()=>editPair(number(kern,-32768,32767)))),removePair=button('Remove pair exception',action(status,()=>editPair(null)));right.append(apply,pair,kern.element,pairStatus,setPair,removePair);
    const ac={signal:s.signal};line.input.addEventListener('input',action(status,refresh),ac);size.input.addEventListener('input',paint,ac);mode.input.addEventListener('change',action(status,refresh),ac);
    choices.addEventListener('keydown',e=>{const next=e.key==='ArrowRight'?index+1:e.key==='ArrowLeft'?index-1:e.key==='Home'?0:e.key==='End'?run.items.length-1:null;if(next!==null){e.preventDefault();choose(next,true);}},ac);
    const off=s.doc.changed.subscribe(()=>{if(s.alive())action(status,refresh)();});d.element.addEventListener('close',off,{once:true});
    d.body.append(layout,status);d.footer.append(button('Undo',action(status,()=>{s.check();app.history.undo();})),button('Redo',action(status,()=>{s.check();app.history.redo();})),button('Edit selected outline',action(status,()=>{s.check();const item=run.items[index];if(item&&!item.missing){d.close();app.selectGlyph(item.glyphId);app.activate('glyph');}})),button('Done',d.close));refresh();return d;
}

export function showFeatureVariations(app){
    const d=dialog('Conditional OpenType features',{wide:true,className:'cf-workflow-dialog',subtitle:'Author axis-conditional GSUB and GPOS. Condition sets use design coordinates; matching uses avar-normalized inclusive bounds. The first matching set wins per layout table.'}),s=lifetime(app,d),status=statusBox(),revision=s.doc.revision,draft=app.featureText.value;
    const layout=el('div','cf-workflow-columns'),form=el('div','cf-workflow-properties'),main=el('div','cf-workflow-main'),axis=field('Condition axis',s.doc.data.axes[0]?.tag,{options:s.doc.data.axes.map(a=>({value:a.tag,label:`${a.name||a.tag} (${a.tag})`}))}),label=field('Condition name','Heavy'),tag=field('Conditional feature','rvrn',{options:['rvrn','calt','liga','kern']}),minimum=field('Condition minimum','',{type:'number',step:'any'}),maximum=field('Condition maximum','',{type:'number',step:'any'});
    const names=s.doc.data.glyphs.filter(g=>g.export!==false&&/^[\w.$][\w.$-]*$/.test(g.name)).map(g=>g.name),target=field('Input glyph',names.includes('A')?'A':names[0],{options:names}),replacement=field('Output / right glyph',names.includes('V')?'V':names[1],{options:names}),adjust=field('Conditional kerning',-80,{type:'number',min:-32768,max:32767,step:1});
    const textarea=el('textarea','cf-advanced-code');textarea.setAttribute('aria-label','Conditional feature source');textarea.value=draft;textarea.spellcheck=false;
    const text=field('Conditional proof text','AVAV'),proof=el('div','cf-attachment-proof');proof.setAttribute('aria-label','Compiled conditional proof');proof.setAttribute('role','img');proof.hidden=true;let face=null,generation=0;
    const axes=el('div','cf-workflow-axis-controls'),location=Object.fromEntries(s.doc.data.axes.map(a=>[a.tag,a.default])),active=el('p','cf-mono');
    function renderProof(){proof.textContent=text.input.value;proof.style.fontVariationSettings=Object.entries(location).map(([tag,value])=>`"${tag}" ${value}`).join(',');
        try{const parsed=parseFeatures(textarea.value,names),sets=normalizeFeatureConditions(parsed.conditionSets,s.doc.data.axes),match=[...new Set(parsed.variations.map(v=>v.conditionSet))].filter(name=>matchFeatureCondition(sets.get(name),s.doc.data.axes,location));active.textContent=match.length?'Matching sets: '+match.join(' → ')+' (first relevant set per table)':'No condition matches; default features';}catch{active.textContent='Compile to validate the current feature source';}}
    for(const a of s.doc.data.axes){const slider=field('Proof '+(a.name||a.tag),a.default,{type:'range',min:a.min,max:a.max,step:(a.max-a.min)/1000||1}),value=el('output','cf-mono',String(a.default));slider.element.append(value);slider.input.addEventListener('input',()=>{location[a.tag]=Number(slider.input.value);value.textContent=String(location[a.tag]);renderProof();},{signal:s.signal});axes.append(slider.element);}
    function check(){s.check();if(s.doc.revision!==revision||app.featureText.value!==draft)throw new Error('Source or feature draft changed. Reopen this editor before applying.');}
    function resetRange(){const a=s.doc.data.axes.find(a=>a.tag===axis.input.value);minimum.input.value=String(a.default);maximum.input.value=String(a.max);}
    axis.input.addEventListener('change',resetRange,{signal:s.signal});tag.input.addEventListener('change',()=>adjust.element.hidden=tag.input.value!=='kern',{signal:s.signal});resetRange();adjust.element.hidden=true;
    const insert=button('Append conditional rule',action(status,()=>{check();const name=label.input.value.trim();if(!/^[A-Za-z_][\w.]*$/.test(name)||name==='NULL')throw new Error('Use a distinct condition name beginning with a letter');const a=s.doc.data.axes.find(a=>a.tag===axis.input.value),min=number(minimum,a.min,a.max),max=number(maximum,a.min,a.max);if(min>max)throw new Error('Condition minimum must not exceed maximum');const p=parseFeatures(textarea.value,names);if(Object.hasOwn(p.conditionSets,name))throw new Error('Condition name already exists; edit its existing variation block');
        const t=tag.input.value,rule=t==='kern'?`pos \\${target.input.value} \\${replacement.input.value} ${number(adjust,-32768,32767)};`:`sub \\${target.input.value} by \\${replacement.input.value};`;
        textarea.value+=`\nconditionset ${name} {\n  ${a.tag} ${min} ${max};\n} ${name};\nvariation ${t} ${name} {\n  ${rule}\n} ${t};\n`;status.textContent='Rule appended to the private draft. Compile or Apply to validate.';invalidateProof();renderProof();}));
    async function compile(apply){check();const n=++generation,source=textarea.value,snapshot=structuredClone(s.doc.data);snapshot.features=source;status.textContent='Compiling variable layout in the compiler worker…';
        const result=await app.compiler.compile(snapshot,{format:'variable',validate:true},{key:s.key,signal:s.signal,priority:2});check();if(n!==generation||textarea.value!==source)return;
        if(apply){app.history.execute('Apply conditional OpenType features',()=>s.doc.data.features=source);app.featureText.value=source;d.close();return;}
        const family='CF_condition_'+uid().replace(/\W/g,''),next=new FontFace(family,result.bytes,{weight:'1 1000'});await next.load();check();if(n!==generation||textarea.value!==source)return;if(face)document.fonts.delete(face);face=next;document.fonts.add(face);proof.style.fontFamily=`"${family}"`;proof.hidden=false;proof.dataset.ready='true';renderProof();status.textContent='Compiled variable font loaded. Move an axis to test the conditional substitution or positioning.';
    }
    function invalidateProof(){generation++;app.compiler.cancelKey(s.key);proof.hidden=true;delete proof.dataset.ready;if(face)document.fonts.delete(face);face=null;}
    textarea.addEventListener('input',()=>{invalidateProof();renderProof();},{signal:s.signal});text.input.addEventListener('input',renderProof,{signal:s.signal});d.element.addEventListener('close',invalidateProof,{once:true});
    form.append(axis.element,label.element,minimum.element,maximum.element,tag.element,target.element,replacement.element,adjust.element,insert,el('p','cf-muted','The full draft accepts multi-axis AND conditions, named/contextual lookups, script/language selection, and a NULL fallback. Ordinary feature rules remain active; selected variation rules add lookups.'));
    main.append(textarea,text.element,axes,active,proof);layout.append(form,main);d.body.append(layout,status);d.footer.append(button('Cancel',d.close),button('Compile conditional proof',action(status,()=>compile(false))),button('Apply feature source',action(status,()=>compile(true)),{className:'primary'}));renderProof();return d;
}

export function showCollectionBuilder(app,{files:initialFiles=[]}={}){
    const d=dialog('Font collection builder',{wide:true,className:'cf-workflow-dialog',subtitle:'Pack selected masters or local font files into a shared-table TTC/OTC. Face extraction rebuilds standalone checksums and invalidates obsolete digital signatures.'}),s=lifetime(app,d),status=statusBox(),layout=el('div','cf-workflow-columns'),main=el('div','cf-workflow-main'),form=el('div','cf-workflow-properties');
    const format=field('Collection outline format','ttf',{options:[{value:'ttf',label:'TrueType · TTC'},{value:'otf',label:'CFF · OTC'},{value:'cff2',label:'CFF2 · OTC'}]}),version=field('Collection version','2',{options:['1','2']}),filename=field('Collection file name',s.doc.info.familyName.replace(/[^\w-]/g,'_')),files=field('Add local fonts / collection','',{type:'file'});files.input.multiple=true;files.input.accept='.ttf,.otf,.ttc,.otc';
    const entries=(initialFiles.length?[]:s.doc.data.masters).map(m=>({id:uid('face'),masterId:m.id,label:m.name,included:true,bytes:null}));const rows=el('div','cf-collection-rows'),details=el('p','cf-mono');let output=null,busy=false,generation=0,selected=entries[0]?.id;
    const sourceDraft=app.featureText.value,revision=s.doc.revision;
    function validSource(){s.check(false);if(entries.some(e=>e.included&&e.masterId)&&(s.doc.revision!==revision||app.featureText.value!==sourceDraft))throw new Error('The source changed. Reopen the collection builder to capture current masters.');}
    function invalidate(){generation++;output=null;for(const e of entries)delete e.compiled;save.disabled=true;app.compiler.cancelKey(s.key);details.textContent='Build to inspect table sharing';}
    function render(){rows.replaceChildren();for(const [i,e]of entries.entries()){const row=el('div','cf-collection-row'),check=el('input');check.type='checkbox';check.checked=e.included;check.disabled=busy;check.setAttribute('aria-label',`Include ${e.label}`);check.addEventListener('change',()=>{e.included=check.checked;invalidate();},{signal:s.signal});const choose=button(e.label,()=>{selected=e.id;render();});choose.className='cf-collection-select';choose.setAttribute('aria-pressed',String(selected===e.id));
            const up=button('↑',()=>{[entries[i-1],entries[i]]=[entries[i],entries[i-1]];invalidate();render();},{title:`Move ${e.label} up`}),down=button('↓',()=>{[entries[i],entries[i+1]]=[entries[i+1],entries[i]];invalidate();render();},{title:`Move ${e.label} down`}),remove=button('Remove',()=>{entries.splice(i,1);if(selected===e.id)selected=entries[0]?.id;invalidate();render();});up.setAttribute('aria-label',`Move face ${i+1} up`);down.setAttribute('aria-label',`Move face ${i+1} down`);remove.setAttribute('aria-label',`Remove face ${i+1}`);up.disabled=busy||i===0;down.disabled=busy||i===entries.length-1;remove.disabled=busy;row.append(check,choose,el('span','cf-mono',e.bytes?`${e.bytes.length.toLocaleString()} bytes`:'Source master'),up,down,remove);rows.append(row);}
        const selectedEntry=entries.find(e=>e.id===selected);extract.disabled=open.disabled=busy||!(selectedEntry?.bytes||selectedEntry?.compiled);build.disabled=busy;files.input.disabled=busy;format.input.disabled=busy;version.input.disabled=busy;}
    async function addFiles(provided=null){s.check(false);const chosen=[...(provided||files.input.files||[])];if(chosen.reduce((n,f)=>n+f.size,0)>64*1024*1024)throw new RangeError('Selected files exceed 64 MiB');if(!chosen.length)return;busy=true;invalidate();render();try{const added=[];let expanded=entries.reduce((n,e)=>n+(e.bytes?.length||0),0);const reserve=n=>{expanded+=n;if(expanded>128*1024*1024)throw new RangeError('Expanded collection faces exceed 128 MiB');};for(const file of chosen){if(file.size>64*1024*1024)throw new RangeError('Local font input is limited to 64 MiB');const raw=new Uint8Array(await file.arrayBuffer());s.check(false);if(raw.length>=4&&String.fromCharCode(...raw.subarray(0,4))==='ttcf'){
                    const collection=readCollection(raw);for(const f of collection.faces)reserve(12+16*f.tables.length+f.tables.reduce((n,t)=>n+Math.ceil(t.length/4)*4,0));extractCollectionFaces(raw).forEach((bytes,i)=>added.push({id:uid('face'),label:`${file.name} · face ${i+1}`,included:true,bytes}));
                }else{reserve(raw.length);const valid=encodeCollection([raw]);readCollection(valid);added.push({id:uid('face'),label:file.name,included:true,bytes:extractCollectionFace(valid,0)});}}
            if(entries.length+added.length>256)throw new RangeError('Collections are limited to 256 faces');entries.push(...added);selected=added[0]?.id??selected;status.textContent=`Added ${added.length} verified faces. No font data was uploaded.`;
        }finally{busy=false;if(s.alive()){files.input.value='';render();}}}
    async function compile(){validSource();busy=true;invalidate();const n=generation;render();try{const included=entries.filter(e=>e.included);if(!included.length)throw new Error('Select at least one face');const binaries=[];let totalBytes=0;
            for(const [i,e]of included.entries()){status.textContent=`Compiling face ${i+1} of ${included.length}…`;let bytes=e.bytes;if(!bytes){const source=structuredClone(s.doc.data);source.features=sourceDraft;source.info.styleName=e.label;const result=await app.compiler.compile(source,{format:format.input.value,masterId:e.masterId,validate:true},{key:s.key,signal:s.signal,priority:1});bytes=result.bytes;}
                validSource();if(n!==generation)return;totalBytes+=bytes.length;if(totalBytes>128*1024*1024)throw new RangeError('Compiled collection faces exceed 128 MiB');e.compiled=bytes;binaries.push(bytes);}
            const bytes=encodeCollection(binaries,{version:Number(version.input.value)}),decoded=readCollection(bytes);output=bytes;save.disabled=false;
            const standalone=binaries.reduce((n,b)=>n+b.length,0),unique=new Set(decoded.faces.flatMap(f=>f.tables.map(t=>`${t.offset}:${t.length}`))).size;
            details.textContent=`${decoded.faces.length} faces · ${bytes.length.toLocaleString()} bytes · ${unique} unique table ranges · ${standalone-bytes.length} bytes smaller than separate fonts`;
            status.textContent='Collection built and checksums verified. Existing glyph numbering and opaque tables were retained.';
        }finally{busy=false;if(s.alive())render();}}
    const build=button('Build collection',action(status,compile),{className:'primary'}),save=button('Download collection',action(status,()=>{s.check(false);if(!output)throw new Error('Build a collection first');const c=readCollection(output),ext=c.faces.some(f=>f.flavor===0x4f54544f)?'otc':'ttc';download(output,(filename.input.value||'Collection').replace(/[\\/:*?"<>|]/g,'_')+'.'+ext,'font/collection');})),extract=button('Extract selected face',action(status,()=>{s.check(false);const e=entries.find(e=>e.id===selected);const bytes=e?.bytes||e?.compiled;if(!bytes)throw new Error('Import or compile the selected face first');const ext=String.fromCharCode(...bytes.subarray(0,4))==='OTTO'?'otf':'ttf';download(bytes,e.label.replace(/[^\w-]/g,'_')+'.'+ext,ext==='ttf'?'font/ttf':'font/otf');status.textContent='Standalone face extracted with a rebuilt checksum.';}));
    const open=button('Open selected face',action(status,async()=>{s.check(false);const e=entries.find(e=>e.id===selected),bytes=e?.bytes||e?.compiled;if(!bytes)throw new Error('Import or compile a face first');if(s.doc.dirty&&!confirm('Replace the current font with this extracted face? Download your source project first for a portable backup.'))return;const ext=String.fromCharCode(...bytes.subarray(0,4))==='OTTO'?'otf':'ttf';d.close();await app.openFile(new File([bytes],e.label+'.'+ext));}));
    files.input.addEventListener('change',action(status,addFiles),{signal:s.signal});format.input.addEventListener('change',invalidate,{signal:s.signal});version.input.addEventListener('change',invalidate,{signal:s.signal});save.disabled=true;
    form.append(format.element,version.element,filename.element,files.element,extract,open,el('p','cf-muted','Local binary faces keep their format, so mixed collections are allowed. Identical same-tag tables are shared only after byte comparison. Signed fonts lose their invalidated DSIG; glyph IDs are not renumbered. No system font files are accessed.'));
    main.append(el('h3','','Collection faces'),rows,details);layout.append(main,form);d.body.append(layout,status);d.footer.append(button('Close',d.close),build,save);invalidate();render();if(initialFiles.length)action(status,()=>addFiles(initialFiles))();return d;
}
